### ISSUE TITLE
How to connect database?

### ISSUE THREAD

**Issue by jollychang** [vbkunin/itop-docker#10]
What's the host and password?
Should i need create a new database?
![image](https://user-images.githubusercontent.com/64213/48328728-58834380-e680-11e8-9781-4dd80435e166.png)

I can't connect to mysql in docker ?

`sudo docker ps
`![image](https://user-images.githubusercontent.com/64213/48328784-9da77580-e680-11e8-8894-92bf76f1c9bb.png)

Thanks

**Comment by jollychang** [comment]
Fixed, Thanks!

**Comment by yrsdi** [comment]
i've same problem., how to the way?

**Comment by vbkunin** [comment]
And what's the problem? Can't find host/login/pwd? Can't create a db? Can't connect to mysql?
