### ISSUE TITLE
db username and password clarification request

### ISSUE THREAD

**Issue by gittyhubbyfrankybobby** [vbkunin/itop-docker#14]
I ran the command 
`sudo docker logs my-itop | grep -C4 "mysql -uadmin -p"`
and spent way too much time thinking the username was "uadmin" and the password was "pxxxxxxx"
I figured it out, but it might be nice to notate for future users that they should remove the preceding U and P from the username and password respectively during the db setup.

Keep up the great work, though. Thanks.

**Comment by vbkunin** [comment]
Hi @gittyhubbyfrankybobby!
Yes, it makes sense.
