### ISSUE TITLE
i try to use your docker image in Azure webapp  

### ISSUE THREAD

**Issue by ghost** [vbkunin/itop-docker#15]
I created a webapp with your docker image.
I have access to iTop but, when i want to install it, i have a PHP error :

Fatal error: Uncaught ConfigException: Could not find configuration file: file = /var/www/html/conf/production/config-itop.php in /var/www/html/core/config.class.inc.php:1384 Stack trace: #0 /var/www/html/core/config.class.inc.php(1401): Config->CheckFile('configuration', '/var/www/html/c...') #1 /var/www/html/core/config.class.inc.php(1354): Config->Load('/var/www/html/c...') #2 /var/www/html/setup/wizardsteps.class.inc.php(2537): Config->__construct('/var/www/html/c...') #3 /var/www/html/setup/wizardcontroller.class.inc.php(191): WizStepDone->Display(Object(SetupPage)) #4 /var/www/html/setup/wizardcontroller.class.inc.php(132): WizardController->DisplayStep(Object(WizStepDone)) #5 /var/www/html/setup/wizardcontroller.class.inc.php(263): WizardController->Next() #6 /var/www/html/setup/index.php(61): WizardController->Run() #7 {main} thrown in /var/www/html/core/config.class.inc.php on line 1384

Can you help me please?

**Comment by vbkunin** [comment]
What is webapp? What is the tag on the image?

**Comment by ghost** [comment]
Hi,

I used your itop Docker images (2.6.1 base)
docker pull vbkunin/itop

https://hub.docker.com/r/vbkunin/itop



And Azure webapp is a PaaS cloud service :

https://azure.microsoft.com/fr-fr/blog/webapp-for-containers-overview/


If you can't help me, can you provide me the access to your Docker images ?


Regards.

F.
0645153541

________________________________

**Comment by vbkunin** [comment]
Do you have the same error running the image on you local machine?
Sorry, I've never used Azure and can't help with it. Which kind of access do you want? All my images are on this github repo. Switch branches to get other tags.
