### ISSUE TITLE
Docker volume mounting of container to localhost

### ISSUE THREAD

**Issue by patrickjeried** [vbkunin/itop-docker#16]
Hi im trying to mount the volume of ITop container to my local via compose file but it failed. 
heres a sample : 

itop:
    image: vbkunin/itop:2.6.1
    restart: always
    ports:
      - "82:80"
    networks:
      SAMPLE_NETWORK:
        aliases:
          - SAMPLE_ITOP
    volumes:
      - ${DIRECTORY}:/var/www/html/

//The $DIRECTORY variable is my local connection directory.  

Thanks!

**Comment by vbkunin** [comment]
And what do you have as a result? There are errors?

**Comment by patrickjeried** [comment]
Hey man it's all good now forgot to update. problem is my mounting of container volume to my machine. needed to clear all volumes thanks!
