### ISSUE TITLE
Can't upgrade to iTop 2.7.0-beta2 because small PHP values

### ISSUE THREAD

**Issue by lazki** [vbkunin/itop-docker#17]
When trying to upgrade using the new 'Application Upgrade' Menu, itop says:

```
The upload max size seems too small for update. Please change the PHP configuration.
PHP ini value post_max_size: 8M
PHP ini value upload_max_filesize: 2M
```
![imagen](https://user-images.githubusercontent.com/12832159/76914757-049ef500-689a-11ea-906e-e85e22953cdb.png)

Perhaps php.ini should be pre-configured to allow bigger file sizes.

Thanks in advance!

**Comment by vbkunin** [comment]
Yes, you should edit these params in php.ini inside the container or mount your php.ini when creating a new container.

`$ sudo docker exec -it your-container-name bash`
`$ vi /etc/php/7.3/php.ini`

**Comment by vbkunin** [comment]
Check out the recommendations: https://www.itophub.io/wiki/page?id=2_7_0%3Ainstall%3Aphp_and_mysql_configuration#php_mysql_mariadb_settings.
