### ISSUE TITLE
504 Gateway time-out 

### ISSUE THREAD

**Issue by doyoungim999** [vbkunin/itop-docker#18]
Hi, 
I am deploying itop container  on openshift 4.3 now. 
During the deployment, i got the 504 Gateway time-out gateway error. 
I changed max_execution_timeout=600 in php.ini and change Timeout=60 in apache2.conf. 
However i cannot resolve the issue. 
What kind of solution can I try more? 
![image](https://user-images.githubusercontent.com/6082088/79844823-c8a60500-83ee-11ea-853c-022b43311ccd.png)

**Comment by vbkunin** [comment]
Hi! I've never worked with openshift, but I think the problem isn't with apache or php execution timeouts. 504 error means that your proxy/gateway didn't get a response from apache in time. If you're using nginx as a proxy check the *_timeout params:
```
server {
...
    proxy_connect_timeout       600;
    proxy_send_timeout          600;
    proxy_read_timeout          600;
    send_timeout                600;
...
}
```

**Comment by doyoungim999** [comment]
Thank you so much about your comment.
I resolved by setup timeout in openshift route. 

[user1@bm2 ~]$ oc annotate route itop \
>   --overwrite haproxy.router.openshift.io/timeout=600s

**Comment by peleforo** [comment]
Bonjour j'essaie de déployer itop sur mon server NAS SYNOLOGY mais il met le même problème pouvez-vous m'aider
