### ISSUE TITLE
Itop-Docker

### ISSUE THREAD

**Issue by cebarriosa** [vbkunin/itop-docker#19]
Hi, When I'm doing the installation. The app give me a Error:No connection to the database. I tryed with mysql and without mysql

**Comment by Ascl3pi0s** [comment]
In my case, I had to add the following parameter to the command `-p 3306:3306`,  this will map the MySQL port from the docker container to the host port 3306.

The command I ran is:

`sudo docker run -d -p 8000:80 -p 3306:3306 --name=my-itop vbkunin/itop:2.7.0-beta`

Then in the configuration for database server connection is the web interface, I used `0.0.0.0:3306` as the server name.

Note: I used this solution only for Demo/Testing purpose, these changes may not be good to use in a production environment.

**Comment by vbkunin** [comment]
@cebarriosa what actions do you perform and what results do you get (step by step)?
@Ascl3pi0s the mysql port mapping is not needed for installation. It's only for testing and development purposes.
