### ISSUE TITLE
How to upgrade?

### ISSUE THREAD

**Issue by netlol** [vbkunin/itop-docker#20]
Hello,
I used vbkunin/itop:2.6.1 to build my system (with command docker run -d -p 8000:80 -v d:\temp\storage\mysql-itop:/var/lib/mysql --name=itop vbkunin/itop:2.6.1)
I would like upgrade it to 2.7.0.
I changed the command to 'docker run -d -p 8000:80 -v d:\temp\storage\mysql-itop:/var/lib/mysql --name=itop vbkunin/itop:2.7.0'.
At setup page I cann't choose 'Upgrade an existing iTop instance', 
![2020-07-12_094143](https://user-images.githubusercontent.com/33304953/87237075-1e091580-c424-11ea-82af-1c8f05691a80.png)
how can I do the upgrade job?
Thanks!

**Comment by vbkunin** [comment]
Hi, 
in addition to the mysql data folder, you had to persist the configuration file (/var/www/html/conf/production/config-itop.php) and extensions folder (if you have any extensions installed). iTop checks the presence of the configuration file to decide which actions you can perform (install/update).

**Comment by olegenii** [comment]
is it possible to expose config-itop.php for storing it on the Host?

**Comment by vbkunin** [comment]
Да, конечно!

**Comment by olegenii** [comment]
правильно ли я понимаю, что надо заэкспозить из контейнера содержимое /var/www/html в папку хоста, предварительно положив в эту папку последнюю версию itop, взятую с git?

**Comment by vbkunin** [comment]
Если задача сохранить конфиг config-itop.php на хосте, то его и надо пробрасывать в контейнер. Или директорию /var/www/html/conf.
