### ISSUE TITLE
[Question] Plans for releasing 2.7.1?

### ISSUE THREAD

**Issue by favna** [vbkunin/itop-docker#21]
iTop recently (7th of August) released version 2.7.1 of their product which includes some much needed bugfixes. Could you give me an update on when you're planning to release an update to your docker image that includes this version? Thanks!

**Comment by vbkunin** [comment]
I plan to do it right now! Images are being built at the moment, so be patient 🤫

**Comment by vbkunin** [comment]
Done🎉🎉🎉

**Comment by favna** [comment]
tyvm!
