### ISSUE TITLE
Unable to install new ITOP setup under docker

### ISSUE THREAD

**Issue by zutesmog** [vbkunin/itop-docker#25]
Hi

I have been using your itop docker image since Jun (for local development).  Really appreciate the effort you  have put into this.

My current local container works fine. 

I wanted to start a new clean environment but find that with any new container with either :2.7.0 or :latest the install option is never accessible. In addition the acknowledgement of licenses is not visible.

The only thing in the browser console is 

_Uncaught SyntaxError: Unexpected identifier   ajax.document.php:1 
Could not find configuration file: file = /var/www/html/conf/production/config-itop.php_

I don't think that is the problem, though.

Will keep investigating, but this problem seems to be repeatable (a colleague is also experiencing the exact same problem), and the process of starting clean (whole new local container) was working a few weeks back.

This suggests a possible change in something your Dockerfile is dependant on, as I see your commits are pre-date this problem occurring, and we have successfully run the image from scratch since those commits.

Thanks

Tim

**Comment by zutesmog** [comment]
Hi

Ok on further investigation, the problem is just one of css.  
The `<ul>`  with all of the license information is now very long, and it is hiding the acceptance of the license checkbox, so the "Next" button is never enabled.  (setting height of the ul explicitly, shows the checkbox).

Sorry for bothering you.  It probably means it's an issue for Combodo and the installer.

Thanks

T

**Comment by ponmuthu** [comment]
is there any work around to solve this "Next" Button grayed out  issue ?

**Comment by vbkunin** [comment]
It's not a problem of the docker image. Try to contact Combodo.
