### ISSUE TITLE
How to use the image with persistent config

### ISSUE THREAD

**Issue by KpuCko** [vbkunin/itop-docker#29]
Hello,
I'm trying to use this image in production, unfortunately this seems to not work for me, or I simply can't understand how it works.

For example I ran the image by using this command:

`docker run --detach \
  --hostname sofk-itop01.home.lan \
  --network vlan30 --ip 192.168.0.20 \
  --name sofk-itop01.home.lan \
  --restart on-failure \
  --volume sofk-itop01-mysql:/var/lib/mysql \
  --volume sofk-itop01-config:/var/www/html/conf/production \
  --volume sofk-itop01-addons:/var/www/html/extensions \
  vbkunin/itop
`

And the issues I got are:

`: No such file or directory in /var/www/html/core/metamodel.class.php on line 6377
[Mon Feb 22 11:02:49.348175 2021] [php7:error] [pid 299] [client 192.168.0.21:37322] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/env-production/dictionaries/languages.php' (include_path='/var/www/html/lib/pear/archive_tar:/var/www/html/lib/pear/console_getopt:/var/www/html/lib/pear/pear-core-minimal/src:/var/www/html/lib/pear/pear_exception:.:/usr/share/php') in /var/www/html/core/metamodel.class.php on line 6377
`

Why I use all of these volumes? Because I want to have my config persist during image deployment.
Same applies for database and extensions.

Is there a logic implemented in the image to check if existing config is specified or database is already created?
I start to thing this image is not production ready and cannot be used with persistent storage. Correct me if I wrong.

**Comment by vbkunin** [comment]
Hi! Of course, this image is not for production use. If you want to use something in production, first of all, you should be able to customize it according your own security and performance requirements. Obviously, this image cannot be configured in any way. So you can use it at your own risk in any environment))

**Comment by vbkunin** [comment]
Of course, the iTop checks whether the configuration file is present in its directory. It the file is present, iTop thinks that it is already installed and tries to load application files from env-production directory and connect to the DB specified in the config. This is how any iTop does, and this behavior has nothing to do with the docker image.
