### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by stefanjarina** [vbkunin/itop-docker#30]
Hello,

I would like to ask, if it is possible to add a license, as according to https://choosealicense.com/no-permission/ without specifically mentioning a license it is forbidden to change the code in any way (even for purpose of pull request)

Was thinking to create a PR for new iTop 3.0.0, but without license not gonna risk it.

Thank you,
S.

**Comment by vbkunin** [comment]
Hi, Štefan,
I've added the MIT license!
