### ISSUE TITLE
Make itop configuration persistent

### ISSUE THREAD

**Issue by AllardKrings** [vbkunin/itop-docker#31]
Hi,

I have tried running the image in my docker-swarm. 

It works well.

But every time I stop and start the container I have to run the initial setup again.

Is there any way to make my confinguration-settings persistent (i.e. in a volume)?

Hoe someone can help.

**Comment by vbkunin** [comment]
Hi, @AllardKrings 
Yes, of course, you can persist the config file by mounting the "/var/www/html/config/production" container folder as a volume.
