### ISSUE TITLE
Plans to support PHP 8.x

### ISSUE THREAD

**Issue by jeitnier** [vbkunin/itop-docker#32]
WIth active support for 7.4 expired and security support expiring at the end of Nov 2022, are there plans to to support iTop with php 8.x?

**Comment by vbkunin** [comment]
You should ask the iTop developers about this. This project only concerns the docker image itself.

**Comment by vbkunin** [comment]
As I see it, PHP 8 support is planned in version 3.0.2:
https://www.itophub.io/wiki/page?id=3_0_0%3Ainstall%3Arequirements#itop_compatibility_list
