### ISSUE TITLE
Running on Synology

### ISSUE THREAD

**Issue by Vmax-conseils** [vbkunin/itop-docker#33]
Hi, 

I know it's specific but i'll try..

I tried to run your docker image on docker/synology, started the wizard, all good, but at least during installation (40%) i obtain an error 405 (screenshot)
![itop](https://user-images.githubusercontent.com/105369850/167867001-d7f3521e-7d60-4d79-a57d-737f098b0054.png)

Do you have any idea for solve it ?

**Comment by vbkunin** [comment]
Hi,
During the installation process, the wizard executes http requests to the backend to check the current percentage of completion. I suppose you nginx proxy server doesn't like some of these requests for some reason ("405 Method not allowed" error indicates to it).

1. Check your browser console to find a problem request and its parameters (method, path etc).
2. Check your nginx logs and config to figure out how the request handling and proxying is performed.
3. Try to googling "synology nginx 405 not allowed", knowing the problem request params.

Unfortunately I've never worked Synology)
