### ISSUE TITLE
failed to activate

### ISSUE THREAD

**Issue by Varick-Wang** [vbkunin/itop-docker#35]
hello~
After running docker run,
```bash
 sudo docker run -id --name=my-itop -p 8080:80 -v /mnt/var/www/html:/var/www/html -v /mnt/var/lib/mysql :/var/lib/mysql --restart=always vbkunin/itop:latest
```
I don't see the next configuration information under http://localhost:8080. And only:
#### index of / Name Last modified Size Description

View html/ no file how to solve?

**Comment by Varick-Wang** [comment]
Oh, I found the problem.
Should be ${dir}:/var/www/html/conf

thanks

**Comment by Varick-Wang** [comment]
Excuse me, why does this happen?

**Comment by vbkunin** [comment]
Hi,
You've replaced the iTop code with the contents of your folder /mnt/var/www/html which is empty.
