### ISSUE TITLE
Create anyone new object result in PHP report error

### ISSUE THREAD

**Issue by lklkxcxc** [vbkunin/itop-docker#4]
`[Wed Dec 06 11:06:43.806752 2017] [:error] [pid 398] [client 192.168.1.163:55316 

] PHP Warning:  Invalid argument supplied for foreach() in /app/core/metamodel.class.php on line 1570, referer: http://cmdb.ops.gaia/pages/UI.php?operation=new&class=WebApplication&c[org_id]=1&c[menu]=ConfigManagementOverview 

[Wed Dec 06 11:06:43.806757 2017] [:error] [pid 398] [client 192.168.1.163:55316 

] PHP Warning:  Invalid argument supplied for foreach() in /app/core/metamodel.class.php on line 1583, referer: http://cmdb.ops.gaia/pages/UI.php?operation=new&class=WebApplication&c[org_id]=1&c[menu]=ConfigManagementOverview 
`

**Comment by vbkunin** [comment]
You forgot about some diagnostic information, didn't you?

**Comment by lklkxcxc** [comment]
Before the full logs detail ：
`[Thu Dec 07 03:09:31.098937 2017] [:error] [pid 125] [client 192.168.1.163:54957] PHP Notice:  Undefined index: m_sStimulus in /app/application/wizardhelper.class.inc.php on line 286, referer: http://cmdb.ops.gaia/pages/UI.php?operation=new&class=WebApplication&c[org_id]=1&c[menu]=ConfigManagementOverview
[Thu Dec 07 03:09:31.098980 2017] [:error] [pid 125] [client 192.168.1.163:54957] PHP Notice:  Undefined index: m_sInitialState in /app/application/wizardhelper.class.inc.php on line 281, referer: http://cmdb.ops.gaia/pages/UI.php?operation=new&class=WebApplication&c[org_id]=1&c[menu]=ConfigManagementOverview
[Thu Dec 07 03:09:31.099014 2017] [:error] [pid 125] [client 192.168.1.163:54957] PHP Notice:  Undefined index:  in /app/core/metamodel.class.php on line 1562, referer: http://cmdb.ops.gaia/pages/UI.php?operation=new&class=WebApplication&c[org_id]=1&c[menu]=ConfigManagementOverview
[Thu Dec 07 03:09:31.099022 2017] [:error] [pid 125] [client 192.168.1.163:54957] PHP Notice:  Undefined index:  in /app/core/metamodel.class.php on line 1567, referer: http://cmdb.ops.gaia/pages/UI.php?operation=new&class=WebApplication&c[org_id]=1&c[menu]=ConfigManagementOverview`



Today I created the same resource again,the result was successful
Why not?
