### ISSUE TITLE
Installation error _getaddresses

### ISSUE THREAD

**Issue by InstaZDLL** [vbkunin/itop-docker#41]
Hello, when I try to install itop, I always get this error and the installation gets stuck at 40%.
am I doing something wrong?

```shell
Warning
: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for itop failed: Name or service not known in
/var/www/html/core/cmdbsource.class.inc.php
on line
180
```

![Screenshot 2023-11-13 185850](https://github.com/vbkunin/itop-docker/assets/72951793/c19c253e-e41c-4d01-9a31-f30596cc593a)

**Comment by MamyNova69** [comment]
Hello, I think your connection to the database is not correct, 
![Capture d’écran 2023-12-21 221231](https://github.com/vbkunin/itop-docker/assets/34945270/78c9930d-b0f4-4281-90b4-6b4d47310011)

My version of a docker-compose.yml

alose give access to your folder 

`sudo chmod -R 777 datas/`

`version: '3'
services:
  itop:
    image: vbkunin/itop:latest-base
    ports:
      - "8000:80"
    volumes:
      - /home/remi/itop/datas/conf:/var/www/html/conf
    restart: unless-stopped

  itop-database:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=itop
      - MYSQL_ROOT_PASSWORD=itopuser
      - MYSQL_TCP_PORT=3307
      - MYSQL_USER=itopuser
      - MYSQL_PASSWORD=itopuser
    ports:
    - "3307:3307"
    expose:
      - 3307
    volumes:
      - /home/remi/itop/datas/mysql:/var/lib/mysql
    restart: unless-stopped`
