### ISSUE TITLE
Production config not exists in container

### ISSUE THREAD

**Issue by MrApelPro** [vbkunin/itop-docker#43]
Version: vbkunin/itop:latest-base (and other versions too)

Uncaught ConfigException: Could not find configuration file: file = /var/www/html/conf/production/config-itop.php in /var/www/html/core/config.class.inc.php:1973 Stack trace: #0 /var/www/html/core/config.class.inc.php(1990): Config->CheckFile() #1 /var/www/html/core/config.class.inc.php(1943): Config->Load() #2 /var/www/html/setup/wizardsteps.class.inc.php(2582): Config->__construct() #3 /var/www/html/setup/wizardcontroller.class.inc.php(224): WizStepDone->Display() #4 /var/www/html/setup/wizardcontroller.class.inc.php(156): WizardController->DisplayStep() #5 /var/www/html/setup/wizardcontroller.class.inc.php(294): WizardController->Next() #6 /var/www/html/setup/wizard.php(69): WizardController->Run() #7 {main} thrown in /var/www/html/core/config.class.inc.php on line 1973

**Comment by vbkunin** [comment]
If you want to get any help, you should provide additional information. This error indicates an incorrect configuration of the docker environment or an unfinished iTop setup procedure.

**Comment by MrApelPro** [comment]
I just started it as you wrote in readme:
sudo docker run -d -p 8000:80 --name=my-itop vbkunin/itop

At least a sample config should appear in container I think, than I can setup as my needs. And I do not found information in readme how to change my environment to work with this - how to place this configuriation file into container and about the content.

First I used with compose, but I try out the image itself. Remove the old one from my server, and start it raw as mentioned before. It seems like a mistake in the image or description.

**Comment by MrApelPro** [comment]
I try demo and production as well. With base image and image with sql also, all of that produce this error: config file not found.

**Comment by vbkunin** [comment]
The config-itop.php file appears after the installation procedure is completed, and not after the container is started. The container is just a php+apache+mysql environment, it does not do anything additional with the iTop application. You must install and configure iTop yourself by following its documentation and the wizard http://localhost:8000/setup/wizard.php.

**Comment by MrApelPro** [comment]
Okay, i see you think I am a noob. But this error occur after the wizard, when press "install".

**Comment by MrApelPro** [comment]
Maybe need to run one of your script, which make configs writable?

**Comment by MrApelPro** [comment]
docker exec my-itop conf-w

**Comment by vbkunin** [comment]
I just checked the procedure from the README:

1. Run in a new terminal `sudo docker run -d -p 8000:80 --name=my-itop vbkunin/itop` and saw the container id.
2. Then run `sudo docker logs my-itop | grep -A7 -B1 "Your MySQL user 'admin' has password:"` to get the mysql admin password.
3. Go to http://localhost:8000/ and I was redirected to http://localhost:8000/setup/wizard.php.
4. Successfully complete the installation wizard.

**Comment by vbkunin** [comment]
> Maybe need to run one of your script, which make configs writable?

No you don't need because you have no configs (according to you error message).

**Comment by vbkunin** [comment]
> Okay, i see you think I am a noob. But this error occur after the wizard, when press "install".

Sorry, but I still don't understand at which step you get the error. And still nothing info about the docker environment config (mounts, volumes, another images if any).

**Comment by MrApelPro** [comment]
> I just checked the procedure from the README:
> 
> 1. Run in a new terminal `sudo docker run -d -p 8000:80 --name=my-itop vbkunin/itop` and saw the container id.
> 2. Then run `sudo docker logs my-itop | grep -A7 -B1 "Your MySQL user 'admin' has password:"` to get the mysql admin password.
> 3. Go to http://localhost:8000/ and I was redirected to http://localhost:8000/setup/wizard.php.
> 4. Successfully complete the installation wizard.

Yes, I try this. With compose and my own database, with database in your container. Just one difference: the setup does not completed, but the error I asked shown. So what is the solution?

**Comment by MrApelPro** [comment]
> > Okay, i see you think I am a noob. But this error occur after the wizard, when press "install".
> 
> Sorry, but I still don't understand at which step you get the error. And still nothing info about the docker environment config (mounts, volumes, another images if any).

I wrote you the command I run, which strongly show the environment: no mounts, volumes, just your container and the port forward rule.

**Comment by vbkunin** [comment]
Have you tried to force the wizard to run?
http://localhost:8000/setup/wizard.php

**Comment by MrApelPro** [comment]
Do not worry about compose, I look for your documentation and follow your steps - without compose and volumes, because when I can get a working solution I can change it to my needs. But following yor steps does not help.

One more thing:
One month ago I can start it. With compose and without any problem. That was a demo. But now I want to start again from zero and not works. This is why I remove the image and all things in connection with your container. But it is not helps me..

I do not know if the source changed or how your container built. So I try it raw, with docker run, without compose and volumes, but still not working. This point I create this issue.

**Comment by vbkunin** [comment]
Are the container and the browser on the same host?

**Comment by MrApelPro** [comment]
> Have you tried to force the wizard to run? http://localhost:8000/setup/wizard.php

My problem is not about starting the wizard. I can press "next" and setup things in wizard, but at the end there is a summarize page and "install" button, and when I press "install" then the error message shown.

**Comment by MrApelPro** [comment]
> Are the container and the browser on the same host?

No. I try to install it on a VPS. With nginx reverse proxy.

**Comment by vbkunin** [comment]
The image was last updated 4 months ago.

> No. I try to install it on a VPS. With nginx reverse proxy.

Try to repeat the installation on the local host.

**Comment by MrApelPro** [comment]
> The image was last updated 4 months ago.
> 
> > No. I try to install it on a VPS. With nginx reverse proxy.
> 
> Try to repeat the installation on the local host.

Ya, thats help. Https make something strange. :)
I make it https after config last time.. Now I want to configure it with that... Than i config it with http and just make the redirect rule after that. thank you!

**Comment by MrApelPro** [comment]
Yes, it works on the server too. Just need to configure it without encryption. Thank you!
